pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "zakee14910/library-system"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/zakee14910/GSCOMP126NCC.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    sh "docker buildx build --platform linux/amd64,linux/arm64 -t zakee14910/library-system:latest ."
                    sh "docker login -u zakee14910 -p Adm1n1strat0r"
                    sh "docker buildx build --platform linux/amd64,linux/arm64 -t zakee14910/library-system:latest --push ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker run --name library-system-container -p 8080:8080 -d ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }
}
